version: '3.4'

volumes:
  prometheus_data:
  grafana_data:

services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "54321:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - microservices-net

  # Referência: https://www.youtube.com/watch?v=K_EI1SxVQ5Q&list=PLZTjHbp2Y7809w3PLM0UE_LgQq6vk49q0&index=3
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge