version: '3.4'

services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "54321:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-net

  admin:
    image: slydeveloper/spring-boot-admin:1.3
    volumes:
      - ./docker-config/admin-application.yml:/opt/spring-boot-admin-docker/application-docker.yml
    ports:
      - "1111:1111"

networks:
  microservices-net:
    driver: bridge