version: '3.4'

volumes:
  prometheus_data:

services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "54321:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge